### ISSUE TITLE
npm install fails for node v14

### ISSUE THREAD

**Issue by jithinktom** [v8/sampling-heap-profiler#58]
````
make: *** [Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jithin1992/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/jithin1992/.nvm/versions/node/v14.15.0/bin/node" "/Users/jithin1992/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jithin1992/Documents/workspace/services/product-search/node_modules/heap-profile
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN product-search@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heap-profile@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heap-profile@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

**Comment by aliqaryan2** [comment]
Having the exact same problem. @ofrobots

**Comment by ofrobots** [comment]
Can you try with the alternative module https://github.com/google/pprof-nodejs?

**Comment by michaele-blend** [comment]
hello @ofrobots and @nolanmar511,

I have submitted a patch here that fixes the compilation issue:

#66

Please let me know if you have any feedback or reservations about merging this, I am happy to address.

**Comment by ankursachdeva11** [comment]
@michaele-blend @srubin

Please merge this PR to fix above node v14 issue: https://github.com/v8/sampling-heap-profiler/pull/57

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information). 

Closing all issues in anticipation of this.
